

services:
  mysql:
    image: mysql:8.0
    container_name: eventdb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: event-booking-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: qa

volumes:
  mysql_data: